obj-y += edf_common.o \
	fp_common.o \
	sched_gsn_edf.o \
	sched_psn_edf.o \
	sched_pfp.o \
	sched_plugin.o \
	sched_pres.o

obj-$(CONFIG_PLUGIN_CEDF) += sched_cedf.o
obj-$(CONFIG_PLUGIN_PFAIR) += sched_pfair.o
