#
# Makefile for LITMUS^RT
#

obj-y     = litmus.o \
	    preempt.o \
	    litmus_proc.o \
	    clustered.o \
	    jobs.o \
	    sync.o \
	    rt_domain.o \
	    fdso.o \
	    ctrldev.o \
	    uncachedev.o


obj-y += common/
obj-y += reservations/
obj-y += sched/
obj-y += locking/
obj-y += tracing/